### ISSUE TITLE
False error box when attempting to save the .musicxml to my local disk

### ISSUE THREAD

**Issue by zhouziqi13** [Nobaiha/EECS2311_Project_G4#43]
**Bug Report Title:**  
False error screen when attempting to save the .musicxml to my local disk
**Reported by:**  
Ziqi Zhou
**Date reported:**  
March 22nd, 2021
**Program (or component) name:**  
Download operation under conversion completion screen
**Configuration(s):**  
_Operating System_: MacOS Big Sur 
_Manufacturer and Model_: MacBook Air (M1, 2020)
_Processor:_ Apple M1
_Memory_: 8 GB (RAM)  
_Graphics Card:_ Apple M1 GPU 8 GB
_JAVA version_: Java-SE 15
_Application Version_: Downloaded from Github master March 22nd. Commit key: https://github.com/Nobaiha/EECS2311_Project_G4/commit/934e1dc4129f031486ed4f1fa80acafb0205a042 
**Report type**:  
Coding Error
**Reproducibility**:  
Yes  
**Severity**:  
Medium
**Problem Summary**:  
An error box claiming download failure pops up during file download, but the file is correctly saved at the desired location. 
**Problem description:**  
After the conversion is complete, the download button appears. After selecting the desired location for the MusicXML file download, an error box claiming download failure pops up, but the file is correctly saved at the desired location. 

***Expected Behaviour***
There should not be any error box, or an alert box claiming the download is successful.

**Steps to Reproduce:**  
Import the master branch in Eclipse from git import 
Right-click on the project -> Gradle -> Refresh Gradle
Click on Run
In the pop-up screen, click on Start.
In the file upload screen, click on Browser -> In the file selection screen, select a text file containing a tablature. 
Click on Convert -> In the conversion completion screen, click on Download -> Select desired saving location in the file selection screen -> Click on Save
You should observe a popup screen with text “There was an error saving your file, please retry”. Yet if you navigate to the file location, you will see the .musicxml file containing the conversion content. 
**New or old bug:**  
New  

### Screenshot
<img width="445" alt="Screen Shot 2021-03-24 at 11 41 07 AM" src="https://user-images.githubusercontent.com/46424591/112339325-eed6c380-8c95-11eb-8882-9e4101f41ad8.png">

**Comment by Nobaiha** [comment]
Hi Doris, thankyou for the report, I can't seem to re-create this bug, could you please provide me with what the console is showing? And can you provide me with the input file too please? Thankyou!

**Comment by zhouziqi13** [comment]
> Hi Doris, thankyou for the report, I can't seem to re-create this bug, could you please provide me with what the console is showing? And can you provide me with the input file too please? Thankyou! 

Hi @Nobaiha ! This bug might be specific to Mac users only. Any input gives me this error box. My group members told me normally on windows it opens the saved file automatically. On my MacBook however, an error box is shown

**Comment by dokdek** [comment]
Issue with M1 macs running Eclipse on Rosetta.  Cannot replicate this issue on my two Intel based macs.
