### ISSUE TITLE
Incorrect Repeated Measure

### ISSUE THREAD

**Issue by ahopk127** [Nobaiha/EECS2311_Project_G4#51]
## Description
The system seems to be placing a repeated measure in the first measure of some text tabs.
## Reproduction
1. Open the application
2. Input the provided text tab
3. Convert and save the tab
## Results
**Expected Result**: The output tab has no repeated measures
**Actual Result**: The output tab has a repeat sign at the end of the first measure
## Details
**Version**: master branch, commit 934E1DC (2021-03-18)
**Platform**: Windows 10, Eclipse 2020-12, OpenJDK 15.0.2
**Priority**: Medium
**Severity**: Medium
## Screenshots
The output rendered in [OpenSheetMusicDisplay](https://opensheetmusicdisplay.github.io/demo/)
![Rendered Output](https://user-images.githubusercontent.com/73263261/112219819-e6ca4580-8bfb-11eb-98f4-42811f67828b.png)
## Files
[Input Tablature](https://github.com/Nobaiha/EECS2311_Project_G4/files/6192786/input-tab.txt)
[Output MusicXML](https://github.com/Nobaiha/EECS2311_Project_G4/files/6192790/output4.txt) *Note: GitHub does not support uploading XML files, so the extension of this file was changed to .txt)*

**Comment by dokdek** [comment]
Fixed in latest commit.
