### ISSUE TITLE
Metadata Resets Unexpectedly

### ISSUE THREAD

**Issue by ahopk127** [Nobaiha/EECS2311_Project_G4#52]
## Description
The key and time signature are unexpectedly reset upon pressing the "Modifications" button.
## Reproduction
1. Open the application
2. Press the "Modifications" button
3. Change the key to B♭ major.
4. Change the time signature to 6/8.
5. Press "Confirm"
6. Press "Modifications" again
## Results
**Expected Result**: The key is B♭ major, and the time signature is 6/8.
**Actual Result**: The key is C major, and the time signature is 4/4.
## Details
**Version**: master branch, commit 934E1DC (2021-03-18)
**Platform**: Windows 10, Eclipse 2020-12, OpenJDK 15.0.2
**Priority**: Medium
**Severity**: Medium
## Notes
 - This bug still occurs if a text tab is loaded into the system

**Comment by ahopk127** [comment]
Similar to issue #45, but the key is also unexpectedly reset.  The title and composer are not reset.

**Comment by dokdek** [comment]
Resolved
