### ISSUE TITLE
Output does not contain specified key or time signature

### ISSUE THREAD

**Issue by ahopk127** [Nobaiha/EECS2311_Project_G4#53]
## Description
The key and time signature set in the "Modifications" section are not reflected in the final version.
## Reproduction
1. Open the application
2. Load the provided text tab
3. Press the "Modifications" button
4. Change the key to B♭ major.
5. Change the time signature to 6/8.
6. Press "Confirm"
7. Press "Convert"
8. Press "Download"
9. Open the generated file in your preferred MusicXML viewer
## Results
**Expected Result**: The time signature of the resulting MusicXML tab is 6/8 and its key is B♭ major
**Actual Result**: The time signature of the resulting MusicXML tab is 4/4 and its key is C major
## Details
**Version**: master branch, commit 934E1DC (2021-03-18)
**Platform**: Windows 10, Eclipse 2020-12, OpenJDK 15.0.2
**Priority**: Medium
**Severity**: High
## Screenshots
![Screenshot 2021-03-23 164137](https://user-images.githubusercontent.com/73263261/112223019-aff62e80-8bff-11eb-9009-f1d593bce031.png)
![Screenshot 2021-03-23 164651](https://user-images.githubusercontent.com/73263261/112223085-cac8a300-8bff-11eb-8418-9249c2f5030d.png)
## Files
[Input Text Tab](https://github.com/Nobaiha/EECS2311_Project_G4/files/6192906/readme-sample-1.txt)
[Output MusicXML](https://github.com/Nobaiha/EECS2311_Project_G4/files/6192910/output10.txt) *Note: GitHub does not support uploading XML files, so the extension of this file was changed to .txt)*

**Comment by ahopk127** [comment]
Similar to issue #44, but the key is also not included.

**Comment by dokdek** [comment]
Resolved
