### ISSUE TITLE
Hammer-On + Chord bug

### ISSUE THREAD

**Issue by hickman-edward-215666811** [Nobaiha/EECS2311_Project_G4#55]
### ID
55
###  Who Raised
Edward Hickman
### Description
A hammer-on and chord at the same time will separate the hammer on from itself, as well as from the chord.
### Reproduction
Input this tab into the system and convert. Import xml file into music application of choice. I used [OpenSheetMusic](https://opensheetmusicdisplay.github.io/demo/) 
```
E|-15h12--------------------------------|
B|--------------------------------------|
G|--------------------------------------|
D|--------------------------------------|
A|--0-----------------------------------|
D|--------------------------------------|
```
OR this file
[hammeron-chord.txt](https://github.com/Nobaiha/EECS2311_Project_G4/files/6192980/hammeron-chord.txt)
### Expected Result
via  [OpenSheetMusic](https://opensheetmusicdisplay.github.io/demo/) 
![image](https://user-images.githubusercontent.com/46533281/112224975-7672f280-8c02-11eb-9795-738474e0ba05.png)

### Actual Result
via  [OpenSheetMusic](https://opensheetmusicdisplay.github.io/demo/) 
![image](https://user-images.githubusercontent.com/46533281/112224992-7d016a00-8c02-11eb-86b1-5407a9ad0c21.png)

### Details
Version: Master branch, commit 934e1dc 
Platform: Windows 10, Eclipse version 2020-12, OpenJDK 15.0.2
Priority: Low
Severity: Low

**Comment by dokdek** [comment]
Expected bug, chords in our program are recognized if the first elements are matching. For this specific case, 1 and 0 should be aligned.
