### ISSUE TITLE
Pull-off start/stop notation bug.

### ISSUE THREAD

**Issue by amirmohamad-yu** [Nobaiha/EECS2311_Project_G4#56]
# Description
If a pull-off sequence(starting with a double digit fret) is preceded by a chord, the system does not properly assign the end fret of the pull-off, and the notes are mismatched in the incorrect order as a result.

# Reproduction
1. Launch application
2. Input the below sample guitar tablature
3. Save to musicxml file
4. Render the file via an external software(In this case, [OpenSheetMusicDisplay](https://opensheetmusicdisplay.github.io/demo/))
* sample input:
```e|-----------|
B|-10p0------|
G|-----------|
D|-----------|
A|--3--------|
E|-----------|
```
* sample output xml from conversion:
  - These are the first 2 notes, with fret 10 and 3. The start and stop of the pull-off notation are notated on the wrong notes.
```
            <note>
                <pitch>
                    <step>A</step>
                    <octave>4</octave>
                </pitch>
                <duration>-1</duration>
                <notations>
                    <technical>
                        <pull-off number="1" type="start">P</pull-off>
                        <string>2</string>
                        <fret>10</fret>
                    </technical>
                    <slur number="1" placement="above" type="start"/>
                </notations>
            </note>
            <note>
                <pitch>
                    <step>C</step>
                    <octave>3</octave>
                </pitch>
                <duration>1</duration>
                <notations>
                    <technical>
                        <pull-off number="1" type="stop"/>
                        <string>5</string>
                        <fret>3</fret>
                    </technical>
                    <slur number="1" type="stop"/>
                </notations>
            </note>
```
* output rendered via [OpenSheetDisplay](https://opensheetmusicdisplay.github.io/demo/)

Renders  | Cases  
------- | ------------------
![image](https://user-images.githubusercontent.com/77291875/112240078-05413880-8c1e-11eb-858b-7e880c2219e0.png) | Result
![image](https://user-images.githubusercontent.com/77291875/112240720-3706cf00-8c1f-11eb-8e2c-6432f38f83ee.png) | Expected

# System/Details
Platform: Windows 10, Eclipse 2020-12 (4.18.0), OpenJDK 15.0.2
Version: master branch, commit 934e1dc
Priority: Medium
Severity: High

**Comment by dokdek** [comment]
Expected bug, chords in our program are parsed if they match on the first element. The 3 should be in line with the 1, not the 0 for the program to recognize a chord.
