### ISSUE TITLE
Incorrect Duration

### ISSUE THREAD

**Issue by Sayed08** [Nobaiha/EECS2311_Project_G4#59]
### Description
When a tab is used to convert into MusicXmL using the application, The converted MusicXML has incorrect durations. 

### Bug Raised By
Sayed Mohammed

### Details
**Platform:** Windows 10 - Eclipse IDE for Java Developers - 2020-09
**version:** Version 2.0
**Priority:** medium
**Severity:** medium

### Reproduction
**1.**  Open your application
**2.**  load the following txt file [Incorrect Duration.txt](https://github.com/Nobaiha/EECS2311_Project_G4/files/6194612/Incorrect.Duration.txt)
**3.** Press Convert

### Results
**1.** **Result Expected:** When the time signature of the MusicXML file is 4/4(which is set automatically or can be set using the modification option on the GUI) the duration of the notes should be 2 because when time-signature is 4/4 each measure should be the duration of one whole note.
**2.** **Actual Result:** When The time signature of the MusicXML is 4/4, The duration of the notes is 2.

 ### ScreenShots
**Actual Result:**
![actual](https://user-images.githubusercontent.com/60377008/112261519-6d097a80-8c42-11eb-926a-c78104a3746e.jpg)

**Result Expected:** 
![expected](https://user-images.githubusercontent.com/60377008/112262178-9aa2f380-8c43-11eb-9e2e-a6de4e84e703.jpg)

### Files
**1.** [Incorrect Duration.txt](https://github.com/Nobaiha/EECS2311_Project_G4/files/6194702/Incorrect.Duration.txt)

**Comment by dokdek** [comment]
Fixed as of latest commit.
