### ISSUE TITLE
Missing Note Type in the converted MusicXML

### ISSUE THREAD

**Issue by Sayed08** [Nobaiha/EECS2311_Project_G4#60]
### Description
When a tab is converted to MusicXML using the application the note type is missing in the musicXML.

### Bug Raised By
Sayed Mohammed

### Details
**Platform:** Windows 10 - Eclipse IDE for Java Developers - 2020-09
**version:** Version 2.0
**Priority:** Medium
**Severity:** low

### Reproduction
**1.**  Open your application
**2.**  load the following txt file [Incorrect NoteType.txt](https://github.com/Nobaiha/EECS2311_Project_G4/files/6195335/Incorrect.NoteType.txt)
**3.** Press Convert

### Results
**1.** **Result Expected:**  when a tab is converted to MusicXML whose time signature is 4/4, then each measure should be the duration of one whole note and each note should have the type ''quarter'' like shown in the screenshot below.
**2.** **Actual Result:** when a tab is converted to MusicXML, the note type is missing in the converted MusicXML file as shown in the screenshot below.

 ### ScreenShots
**Actual Result:**
![actual](https://user-images.githubusercontent.com/60377008/112264032-a0e69f00-8c46-11eb-90e8-b5e426ec868c.jpg)

**Result Expected:** 
![expected](https://user-images.githubusercontent.com/60377008/112276491-312ce000-8c57-11eb-842f-8a072281e757.jpg)

### Files
**1.** [Incorrect NoteType.txt](https://github.com/Nobaiha/EECS2311_Project_G4/files/6195332/Incorrect.NoteType.txt)

**Comment by dokdek** [comment]
This is intended, musicXML does not need a note type to function properly.
