### ISSUE TITLE
Musicxml file opens automatically after pressing download

### ISSUE THREAD

**Issue by hargovindsingh** [Nobaiha/EECS2311_Project_G4#61]
**Reported by:**
Hargovind Singh

**Date reported:**
March 24th, 2021

**Program (or component) name:**
Download screen

**Configuration(s):**
Operating System: Windows 10 Pro 64
Manufacturer and Model: HP Notebook
Processor: Intel® Core™ i5-10210U
Memory: 8 GB (RAM)
JAVA version: Java-SE 15
Application Version: Downloaded from Github master March 24th. Commit key: 934e1dc

**Report type:**
Feature error

**Reproducibility:**
Yes

**Severity:**
Medium

**Problem Summary:**
After pressing the download button on the final screen, the generated ‘musicXML’ file opens automatically in a text editor.

**Expected Behaviour:**
The “Download” feature should simply save the file on my system in a directory of my choosing. 

**Steps to Reproduce:**
Import the master branch in Eclipse from git import
Right-click on the project -> Gradle -> Refresh Gradle
Click on Run
In the pop-up screen, click on Start.
In the file upload screen, click on Browser -> In the file selection screen, select a text file containing a tablature.
Click on convert and then click on download. Enter the name of the new ‘musicXML’ file and then click ‘Save’. You will see the musicXML open in a text editor.

**New or old bug:**
New

**Comment by Nobaiha** [comment]
Hi Hargovind, thankyou for the report. Our program is designed such way that it saves and opens the file in your choice of application (either open in notepad or microsoft edge etc). We did this based on profs comments. 
However we will take your report into consideration and maybe will give the user an option to save and open or just save. Thankyou.
