### ISSUE TITLE
Time signature goes back to default value every time you open the modifications option.

### ISSUE THREAD

**Issue by hargovindsingh** [Nobaiha/EECS2311_Project_G4#63]
**Reported by:**
Hargovind Singh

**Date reported:**
March 24th, 2021

**Program (or component) name:**
Modifications screen

**Configuration(s):**
Operating System: Windows 10 Pro 64
Manufacturer and Model: HP Notebook
Processor: Intel® Core™ i5-10210U
Memory: 8 GB (RAM)
JAVA version: Java-SE 15
Application Version: Downloaded from Github master March 24th. Commit key: 934e1dc

**Reproducibility:**
Yes

**Severity:**
Medium

**Problem Summary:**
After you update the time signature from the 'modifications' menu and press confirm and open the menu again, it shows the original time signature. 

**Expected Behaviour:**
The 'Modifications' menu should show the update time measure.

**Steps to Reproduce:**

Import the master branch in Eclipse from git import
*Right-click on the project -> Gradle -> Refresh Gradle
*Click on Run
*In the pop-up screen, click on Start.
*In the file upload screen, click on Browser -> In the file selection screen, select a text file containing a tablature.
*Click on Modifications and update the time signature to a different value (for example 3/4) and click confirm.
*After you return to the input menu, click the modifications button again and it will show the time signature set at 4/4 and not 3/4.

**New or old bug:**
New

**ScreenShot**
![Capture](https://user-images.githubusercontent.com/61370713/112355210-0eb8b800-8c93-11eb-9671-183d5c52b7b9.PNG)
![Capture](https://user-images.githubusercontent.com/61370713/112355356-2f810d80-8c93-11eb-87cb-57d88036d3be.PNG)
![Capture](https://user-images.githubusercontent.com/61370713/112355498-54758080-8c93-11eb-97b5-3be02d1ae3bc.PNG)

**Comment by dokdek** [comment]
Resolved
